# Loads default set of integrations. Do not remove.
default_config:

cloud:

    # Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# allowlist
homeassistant:
  packages: !include_dir_named packages
  
  allowlist_external_dirs:
#    - '/share/data'
    - "/media"
    - "/tmp"

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.30.33.0/24

notify:
  - name: telegram_family
    platform: telegram
    chat_id: !secret telegram_chat_id_family

  - name: telegram_test
    platform: telegram
    chat_id: !secret telegram_chat_id_test

  - name: telegram_jeroen
    platform: telegram
    chat_id: !secret telegram_chat_id_jeroen
